baseURL: http://localhost.cloudposse.com:1313/
canonifyURLs: true
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
enableEmoji: true
enableMissingTranslationPlaceholders: false
enableRobotsTXT: true
languageCode: en-us
mediaTypes:
  application/algolia:
    suffixes:
    - algolia.json
menu:
  shortcuts:
  - identifier: nav-forum
    name: <i class='fa fa-book'></i> <label>Forum</label>
    pre: <h3>More</h3>
    url: https://ask.sweetops.com
    weight: 10
  - identifier: nav-slack
    name: <i class='fa fa-bullhorn'></i> <label>Slack</label>
    url: https://slack.sweetops.com
    weight: 20
  - identifier: nav-community
    name: <i class='fa fa-bullhorn'></i> <label>Community</label>
    url: https://sweetops.com
    weight: 20
  - identifier: nav-github
    name: <i class='fab fa-github'></i> <label>Our GitHub</label>
    pre: <h3>More</h3>
    url: https://github.com/cloudposse/
    weight: 30
  - identifier: nav-support
    name: <i class='fa fa-question'></i> <label>Support</label>
    pre: <h3>More</h3>
    url: https://cloudposse.com/accelerate
    weight: 50
  - identifier: nav-contact-us
    name: <i class='fa fa-envelope'></i> <label>Contact Us</label>
    url: /documentation/contact-us/
    weight: 70
outputFormats:
  algolia:
    isPlainText: true
    mediaType: application/algolia
    notAlternative: true
  glossary:
    baseName: glossary
    isPlainText: true
    mediaType: application/json
    notAlternative: true
outputs:
  home:
  - HTML
  - RSS
  - algolia
params:
  disableHomeIcon: true
  disableNavChevron: false
  disableSearch: true
  editURL: https://github.com/cloudposse/docs/blob/master
  enableGitInfo: true
  gtmContainerId: GTM-WQWH2XV
  highlightClientSide: false
  menushortcutsnewtab: false
  ordersectionsby: weight
  showVisitedLinks: true
  themeStyle: flex
publishDir: public
pygmentsCodeFences: true
pygmentsStyle: monokailight
related:
  includeNewer: true
  indices:
  - name: keywords
    weight: 150
  - name: author
    toLower: true
    weight: 30
  - name: tags
    weight: 100
  - name: date
    pattern: '2006'
    weight: 10
  threshold: 60
  toLower: true
taxonomies:
  category: categories
  tag: tags
theme: hugo-theme-docdock
title: Cloud Posse Developer Hub
