// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  modules: [
    'index',
    {
      type: 'autogenerated',
      dirName: 'catalog'
    }
  ],
};

module.exports = sidebars;
