name: 👽 Atmos Terraform Drift Remediation
run-name: 👽 Atmos Terraform Drift Remediation

on:
  issues:
    types:
      - labeled
      - closed

permissions:
  id-token: write
  contents: read
  issues: write

jobs:
  remediate-drift:
    if: github.event.action == 'labeled' && contains(github.event.issue.labels.*.name, 'apply')
    name: Remediate Drift
    runs-on: 
    - self-hosted
    - terraform
    steps:
      - uses: unfor19/install-aws-cli-action@v1
      - name: Remediate Drift
        uses: cloudposse/github-action-atmos-terraform-drift-remediation@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          action: remediate
          atmos-version: ${{ vars.ATMOS_VERSION }}
          atmos-config-path: ${{ vars.ATMOS_CONFIG_PATH }}

  discard-drift:
    if: >
      github.event.action == 'closed' && (
        contains(github.event.issue.labels.*.name, 'drift') ||
        contains(github.event.issue.labels.*.name, 'error')
      ) &&
      !contains(github.event.issue.labels.*.name, 'remediated')
    name: Discard Drift
    runs-on: ['self-hosted', 'terraform']
    steps:
      - name: Discard Drift
        uses: cloudposse/github-action-atmos-terraform-drift-remediation@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          action: discard
          atmos-version: ${{ vars.ATMOS_VERSION }}
          atmos-config-path: ${{ vars.ATMOS_CONFIG_PATH }}

