name: 👽 Atmos Terraform Apply Matrix (Reusable)
run-name: 👽 Atmos Terraform Apply Matrix (Reusable)

on:
  workflow_call:
    inputs:
      stacks:
        description: "Stacks"
        required: true
        type: string
      sha:
        description: "Commit SHA to apply. Default: github.sha"
        type: string
        required: false
        default: "${{ github.event.pull_request.head.sha }}"
      atmos-version:
        description: The version of atmos to install
        required: false
        default: ">= 1.63.0"
        type: string
      atmos-config-path:
        description: The path to the atmos.yaml file
        required: true
        type: string

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  atmos-apply:
    if: ${{ inputs.stacks != '{include:[]}' }}
    name: ${{ matrix.stack_slug }}
    runs-on: ["self-hosted", "terraform"]
    strategy:
      max-parallel: 10
      fail-fast: false # Don't fail fast to avoid locking TF State
      matrix: ${{ fromJson(inputs.stacks) }}
    ## Avoid running the same stack in parallel mode (from different workflows)
    concurrency:
      group: ${{ matrix.stack_slug }}
      cancel-in-progress: false
    steps:
      - uses: unfor19/install-aws-cli-action@v1

      - name: Apply Atmos Component
        uses: cloudposse/github-action-atmos-terraform-apply@v3
        with:
          component: ${{ matrix.component }}
          stack: ${{ matrix.stack }}
          sha: ${{ inputs.sha }}
          atmos-version: ${{ inputs.atmos-version }}
          atmos-config-path: ${{ inputs.atmos-config-path }}
