name: "👽 Atmos Pro List instances"
run-name: list instances

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

# Avoid running the same workflow in parallel.
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  id-token: write # Required for requesting the JWT (OIDC) token
  contents: read  # Required for actions/checkout

jobs:
  atmos-list-instances:
    name: list instances

    runs-on:
      - "runs-on=${{ github.run_id }}"
      - "runner=small"
      - "tag=list-instances"
      - "private=false"

    steps:
      - uses: runs-on/action@v2

      - name: Install Atmos
        uses: cloudposse/github-action-setup-atmos@v3
        with:
          install-wrapper: false
          atmos-version: ${{ vars.ATMOS_VERSION }}

      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: List instances and upload to Atmos Pro
        shell: bash
        env:
          ATMOS_PRO_WORKSPACE_ID: ${{ vars.ATMOS_PRO_WORKSPACE_ID }}
          ATMOS_PROFILE: "github-plan"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          atmos list instances \
            --upload
