name: 👽 Atmos Terraform Dispatch
run-name: 👽 Atmos Terraform Dispatch

on:
  workflow_dispatch:
    inputs:
      component:
        description: "Atmos Component"
        type: string
      stack:
        description: "Atmos Stack"
        type: string
      plan:
        description: "Terraform Plan"
        type: boolean
        default: true
      apply:
        description: "Terraform Apply"
        type: boolean
        default: false
      distinct_id:
        description: "Distinct ID"


permissions:
  id-token: write
  contents: read

jobs:
  dispatch-id:
    runs-on: 
      - self-hosted
      - terraform
    steps:
      - name: echo Distinct ID ${{ github.event.inputs.distinct_id }}
        run: echo ${{ github.event.inputs.distinct_id }}

  atmos-plan:
    needs: [ "dispatch-id" ]
    if: ${{ inputs.plan }}
    name: Plan (${{ inputs.stack }})
    uses: ./.github/workflows/atmos-terraform-plan-matrix.yaml
    with:
      atmos-version: ${{ vars.ATMOS_VERSION }}
      atmos-config-path: ${{ vars.ATMOS_CONFIG_PATH }}
      stacks: |
        {"include": [
          {"component": "${{ inputs.component }}", "stack": "${{ inputs.stack }}", "stack_slug": "${{ inputs.stack }}-${{ inputs.component }}"}
        ]}
    secrets: inherit

  atmos-apply:
    needs: ["atmos-plan"]
    if: ${{ inputs.apply }}
    name: Apply (${{ inputs.stack }})
    uses: ./.github/workflows/atmos-terraform-apply-matrix.yaml
    with:
      atmos-version: ${{ vars.ATMOS_VERSION }}
      atmos-config-path: ${{ vars.ATMOS_CONFIG_PATH }}
      stacks: |
        {"include": [
          {"component": "${{ inputs.component }}", "stack": "${{ inputs.stack }}", "stack_slug": "${{ inputs.stack }}-${{ inputs.component }}"}
        ]}
    secrets: inherit

