name: 'Publish GitHub Pages'
description: 'Publish the Hugo-based CloudPosse docs website to GitHub Pages.'
runs:
#  using: 'docker'
#  image: 'Dockerfile'
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
#    - run: ./actions/publish-github-pages/entrypoint.sh
