name: 'Publish GitHub Pages'
description: 'Publish the Hugo-based CloudPosse docs website to GitHub Pages.'
runs:
  using: 'composite'
  steps:
    - run: ./actions/publish-github-pages/entrypoint.sh
      shell: bash
