repositories:
- name: "stable"
  url: "https://kubernetes-charts.storage.googleapis.com"

releases:
- name: "iam"
  namespace: "kube-system"
  labels:
    chart: "kube2iam"
    component: "iam"
    namespace: "kube-system"
    vendor: "jtblin"
    default: "true"
  chart: "stable/kube2iam"
  version: "0.8.5"
  set:
  - name: "tolerations[0].key"
    value: "node-role.kubernetes.io/master"
  - name: "tolerations[0].effect"
    value: "NoSchedule"
  - name: "aws.region"
    value: 'us-west-2'
  - name: "extraArgs.auto-discover-base-arn"
    value: "true"
  - name: "host.iptables"
    value: "true"
  - name: "host.interface"
    value: "cali+"
  - name: "resources.limits.cpu"
    value: "200m"
  - name: "resources.limits.memory"
    value: "256Mi"
  - name: "resources.requests.cpu"
    value: "50m"
  - name: "resources.requests.memory"
    value: "128Mi"
