#
# Hugo Tasks - intended to be run inside container
#

## Start the hugo server for live editing using local environment
hugo/run: components/build
	hugo server $(HUGO_ARGS)

## Generate all static content (outputs to public/) using local environment
hugo/build: components/build
	@[ "$(HUGO_PUBLISH_DIR)" != "/" ] || (echo "Invalid HUGO_PUBLISH_DIR=$(HUGO_PUBLISH_DIR)"; exit 1)
	rm -rf $(HUGO_PUBLISH_DIR)
	hugo --templateMetrics --stepAnalysis --config $(HUGO_CONFIG)


