apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: chartmuseum
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: chartmuseum-service
          servicePort: 80
