name: Build Cloud Posse Docs
inputs:
  aws_region:
    description: "AWS Region for credentials"
    required: true
  iam_role_arn:
    description: "IAM Role ARN with access to S3 bucket origin"
    required: true
  iam_role_session_name:
    description: "Session name to use to assume access to S3 bucket origin"
    default: "cloudposse-docs-ci"
  google_tag_manager:
    description: "Google Tag Manager"
    default: "GTM-ABCD123"
  google_site_verification_id:
    description: "Google Site verification ID"
    default: "preview-github"
  repo_access_token:
    description: "GitHub Token used to access private repos"
    required: true

runs:
  using: composite
  steps:
    # https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws_region }}
        role-to-assume: ${{ inputs.iam_role_arn }}
        role-session-name: ${{ inputs.iam_role_session_name }}

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"
        cache: 'npm'

    # Set same key to restore cache in all jobs
    # Update key once a week - TTL on unused cache is 7 days
    - name: Set Cache Key
      id: cache-key
      shell: bash
      run: |
        CURRENT_WEEK=$(date +'%Y-%U')
        CACHE_KEY="build-website-cache-${CURRENT_WEEK}"
        echo "result=${CACHE_KEY}" >> $GITHUB_OUTPUT

    - name: Cache rendered content
      if: ${{ !contains(github.event.*.labels.*.name, 'no-cache') }}
      uses: actions/cache@v4
      with:
        path: |
          .build-harness
        key: ${{ steps.cache-key.outputs.result }}

    - name: "Initialize Build Harness"
      shell: bash
      run: |
        make init

    # Download pre-built library docs from draft release or latest published release
    - name: "Download Pre-built Library Docs"
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.repo_access_token }}
      run: |
        DOWNLOADED=false

        # Try draft release first
        echo "Checking for draft release..."
        DRAFT_TAG=$(gh release list --repo ${{ github.repository }} --exclude-drafts=false --limit 20 | { grep "Draft" || true; } | head -1 | awk -F'\t' '{print $3}')

        if [ -n "$DRAFT_TAG" ]; then
          echo "Found draft release: ${DRAFT_TAG}"
          if gh release download "${DRAFT_TAG}" \
               --repo ${{ github.repository }} \
               --pattern "library-docs.tar.gz" \
               --dir /tmp 2>/dev/null; then
            echo "Downloaded library docs from draft release"
            DOWNLOADED=true
          else
            echo "Draft release exists but has no library-docs.tar.gz asset"
          fi
        else
          echo "No draft release found"
        fi

        # Fall back to latest published release
        if [ "$DOWNLOADED" = false ]; then
          echo "Downloading from latest published release..."
          if ! gh release download \
                 --repo ${{ github.repository }} \
                 --pattern "library-docs.tar.gz" \
                 --dir /tmp; then
            echo "Error: No library-docs.tar.gz found in any release. Run the 'Generate Library' workflow first."
            exit 1
          fi
          echo "Downloaded library docs from latest published release"
        fi

        echo "Extracting library docs..."
        tar -xzf /tmp/library-docs.tar.gz
        echo "Library docs downloaded and extracted successfully"

    - name: Install Dependencies and Build Website
      shell: bash
      env:
        GOOGLE_TAG_MANAGER: ${{ inputs.google_tag_manager }}
        GOOGLE_SITE_VERIFICATION_ID: ${{ inputs.google_site_verification_id }}
      run: |
        make build-production
