name: github-pages-deployment
on:
  push:
    branches:
    - master
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types:
    - published

defaults:
  run:
    shell: bash +e -x -o pipefail {0}

jobs:
  github-pages-deploy:
    name: "Build Hugo Site and Deploy to GitHub Pages"
    runs-on: ubuntu-latest
    env:
      GITHUB_PAGES_REPO: https://github.com/cloudposse/docs
      GITHUB_PAGES_BRANCH: production
    steps:
    - name: "Checkout source code at current commit"
      uses: actions/checkout@v2
    - name: "Build Hugo Static Site"
      uses: ./actions/publish-github-pages # arbitrary SHA
      env:
        CONTENT:
        HUGO_URL: https://cloudposse.github.io/docs
        HUGO_PUBLISH_DIR: docs
        HUGO_CONFIG: hugo.config.new.yml # this variable is the output location, not the input template location
        HTMLTEST_CONFIG: .htmltest.new.yml # this variable is the output location, not the input template location
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
    - name: "Deploy Hugo Static Site to GitHub Pages"
      uses: cloudposse/actions/github/git-push@modify-git-push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        GITHUB_REPOSITORY: env.GITHUB_PAGES_REPO
        #GIT_DIRECTORY: /tmp/${{ env.GITHUB_PAGES_BRANCH }}/
