name: github-pages-deployment
on:
  push:
    branches:
    - master
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types:
    - published

defaults:
  run:
    shell: bash +e -x -o pipefail {0}

jobs:
  github-pages-deploy:
    name: "Build Hugo Site to GitHub Pages"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout source code at current commit"
      uses: actions/checkout@v2
    - name: "Deploy to GitHub Pages"
      uses: ./actions/publish-github-pages
      env:
        GITHUB_PAGES_REPO: https://github.com/cloudposse/docs
        GITHUB_PAGES_BRANCH: production
        CONTENT:
        HUGO_URL: https://cloudposse.github.io
        HUGO_PUBLISH_DIR: docs
        HUGO_CONFIG: hugo.config.new.yml # this variable is the output location, not the input template location
        HTMLTEST_CONFIG: .htmltest.new.yml # this variable is the output location, not the input template location
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
