name: "🚀 Staging Release"

on:
  workflow_dispatch:

  push:
    branches:
      - "staging"

env:
  AWS_REGION: us-east-2
  IAM_ROLE_ARN: arn:aws:iam::675539733138:role/cplive-plat-ue2-staging-cloudposse-docs-gha
  IAM_ROLE_SESSION_NAME: cloudposse-docs-ci-deploy-staging
  S3_BUCKET_NAME: cplive-plat-ue2-staging-cloudposse-docs-origin
  DEPLOYMENT_HOST: cloudposse-docs.ue2.staging.plat.cloudposse.org
  ALGOLIA_INDEX_NAME: cloudposse-docs.ue2.staging.plat.cloudposse.org
  ALGOLIA_APP_ID: 32YOERUX83
  GOOGLE_TAG_MANAGER: GTM-ABCD123
  GOOGLE_SITE_VERIFICATION_ID: staging-github

# These permissions are needed to interact with the GitHub's OIDC Token endpoint
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: staging
      url: https://${{ env.DEPLOYMENT_HOST }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Website
        uses: ./.github/actions/build-website
        with:
          aws_region: ${{ env.AWS_REGION }}
          iam_role_arn: ${{ env.IAM_ROLE_ARN }}
          iam_role_session_name: ${{ env.IAM_ROLE_SESSION_NAME }}
          google_tag_manager: ${{ env.GOOGLE_TAG_MANAGER }}
          google_site_verification_id: ${{ env.GOOGLE_SITE_VERIFICATION_ID }}
          repo_access_token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Copy Website to S3 Bucket
        run: |
          cd build
          aws sts get-caller-identity
          aws s3 sync . s3://${{ env.S3_BUCKET_NAME }} --delete --exclude "pr-*"
          aws s3 ls s3://${{ env.S3_BUCKET_NAME }}/ --recursive --human-readable --summarize
