name: "Website Deploy Staging Release"

on:
  push:
    branches:
      - main
      - master

env:
  AWS_REGION: us-east-2
  IAM_ROLE_ARN: arn:aws:iam::675539733138:role/cplive-plat-ue2-staging-cloudposse-docs-gha
  IAM_ROLE_SESSION_NAME: cloudposse-docs-ci-deploy-staging
  NODE_OPTIONS: "--max-old-space-size=3000"
  S3_BUCKET_NAME: cplive-plat-ue2-staging-cloudposse-docs-origin
  DEPLOYMENT_HOST: cloudposse-docs.ue2.staging.plat.cloudposse.org
  ALGOLIA_INDEX_NAME: cloudposse-docs.ue2.staging.plat.cloudposse.org
  ALGOLIA_APP_ID: 32YOERUX83
  GOOGLE_TAG_MANAGER: GTM-ABCD123
  GOOGLE_SITE_VERIFICATION_ID: staging-github

# These permissions are needed to interact with the GitHub's OIDC Token endpoint
permissions:
  id-token: write
  contents: read

jobs:
  docs-deploy-release:
    runs-on: ubuntu-latest

    environment:
      name: staging
      url: https://${{ env.DEPLOYMENT_HOST }}

    steps:
      # https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.IAM_ROLE_ARN }}
          role-session-name: ${{ env.IAM_ROLE_SESSION_NAME }}

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: "Checkout 'terraform-aws-components' Repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          repository: cloudposse/terraform-aws-components
          ref: main
          path: tmp/components/terraform-aws-components

      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: "Install Python Dependencies"
        run: |
          make init
          pip install -r scripts/docs-collator/requirements.txt

      - name: "Render Documentation for Terraform Components"
        run: |
          ./scripts/render-docs-for-components.sh

      - name: "Render Documentation for Terraform Modules"
        env:
          PUBLIC_REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          ./scripts/render-docs-for-modules.sh

      - name: "Render Documentation for GitHub Actions"
        env:
          PUBLIC_REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          ./scripts/render-docs-for-github-actions.sh

      - name: Install Dependencies and Build Website
        env:
          GOOGLE_TAG_MANAGER: ${{ env.GOOGLE_TAG_MANAGER }}
          GOOGLE_SITE_VERIFICATION_ID: ${{ env.GOOGLE_SITE_VERIFICATION_ID }}
        run: |
          make init
          make build-staging

      - name: Copy Website to S3 Bucket
        run: |
          cd build
          aws sts get-caller-identity
          aws s3 sync . s3://${{ env.S3_BUCKET_NAME }} --delete --exclude "pr-*"
          aws s3 ls s3://${{ env.S3_BUCKET_NAME }}/ --recursive --human-readable --summarize
