name: "Website Deploy Release"

on:
  workflow_dispatch:

  release:
    types:
      - published

env:
  AWS_REGION: us-east-2
  IAM_ROLE_ARN: arn:aws:iam::557075604627:role/cplive-plat-ue2-prod-cloudposse-docs-gha
  IAM_ROLE_SESSION_NAME: cloudposse-docs-ci-deploy-release
  S3_BUCKET_NAME: cplive-plat-ue2-prod-cloudposse-docs-origin
  DEPLOYMENT_HOST: docs.cloudposse.com
  ALGOLIA_INDEX_NAME: docs.cloudposse.com
  ALGOLIA_APP_ID: 32YOERUX83

# These permissions are needed to interact with the GitHub's OIDC Token endpoint
permissions:
  id-token: write
  contents: read

jobs:
  website-deploy-release:
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://${{ env.DEPLOYMENT_HOST }}

    steps:
      # https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.IAM_ROLE_ARN }}
          role-session-name: ${{ env.IAM_ROLE_SESSION_NAME }}

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Checkout 'terraform-aws-components' Repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          repository: cloudposse/terraform-aws-components
          ref: master
          path: tmp/components/terraform-aws-components

      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: "Install deps"
        run: |
          make init
          pip install -r scripts/docs-collator/requirements.txt

      - name: "Render docs for components"
        run: |
          ./scripts/render-docs-for-components.sh

      - name: "Render docs for modules"
        env:
          PUBLIC_REPO_ACCESS_TOKEN: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
        run: |
          ./scripts/render-docs-for-modules.sh

      - name: Install Dependencies and Build Website
        env:
          GOOGLE_TAG_MANAGER: ${{ vars.GOOGLE_TAG_MANAGER }}
        run: |
          make deps-production
          make build

      - name: Copy Website to S3 Bucket
        run: |
          cd build
          aws sts get-caller-identity
          aws s3 sync . s3://${{ env.S3_BUCKET_NAME }} --delete
          aws s3 ls s3://${{ env.S3_BUCKET_NAME }} --recursive --human-readable --summarize

      - name: ReIndex with Algolia
        env:
          ALGOLIA_SCRAPER_API_KEY: ${{ secrets.ALGOLIA_SCRAPER_API_KEY }}
        run: |
          ./algolia/reindex.sh
