name: "Website Deploy Release"

on:
  workflow_dispatch:

  schedule:
    - cron: "0 8 * * *"

  release:
    types:
      - published

jobs:
  trigger_documentation_deployment:
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://docs.cloudposse.com

    steps:
      - name: Trigger Documentation Deployment
        run: |
          curl \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.TRIGGER_DOCS_REDEPLOY_WORKFLOW_REFARCH }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/cloudposse/refarch-scaffold/dispatches \
            -d '{"event_type": "redeploy_documentation"}'
