repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com

releases:
- name: charts
  chart: stable/chartmuseum
  version: 1.3.1
  set:
  - name: ingress.enabled
    value: true
  - name: ingress.annotations.kubernetes\.io/ingress\.class
    value: nginx
  - name: ingress.annotations.external-dns\.alpha\.kubernetes\.io/target
    value: ingress.us-west-2.staging.example.com
  - name: ingress.hosts.example\.com[0]
    value: /
